---

- name: Install PostgreSQL GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ barman_repo_download }}"
    fingerprint: "{{ barman_repo_fingerprint }}"

- name: Disable RHEL postgresql as dnf module
  ansible.builtin.command: dnf module disable -y postgresql
  register: result
  changed_when:
    - '"Disabling module streams" in result.stdout'

- name: Install PostgresQL repository
  ansible.builtin.yum:
    name: "{{ barman_repo_rpm }}"
    state: present

- name: Install barman
  ansible.builtin.package:
    name: barman
    state: present

- name: Install PostgreSQL
  ansible.builtin.package:
    name:
      - "postgresql{{ postgresql_version }}"
      - "postgresql{{ postgresql_version }}-server"
