---
# tasks file for coffeesprout.barman

- name: include OS Specific vars
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"
  - main.yml

- include_tasks: "install-{{ ansible_os_family }}.yml"
  tags:
  - install

- name: Barman Global configuration
  ini_file:
    section: "barman"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    dest: "{{ barman_global_configuration_file }}"
    mode: 0644
  with_dict: "{{ barman_default_global_configuration | combine(barman_global_configuration) }}"

- name: Create server configurations
  include_tasks: configure-server.yml
  vars:
    _server: "{{ item }}"
  with_items: "{{ barman_server_configuration }}"
  tags:
  - configure
  - server

#By default 
- name: Ensure minutely cronjob for Barman
  cron:
    user: "{{ barman_user }}"
    name: "barman cron"
    cron_file: barman
    job: "barman cron >> {{ barman_log_directory }}/cron.log"
    state: present
    disabled: "{{ barman_cron_disabled | default(false) }}"
    minute: "{{ barman_cron_schedule.minute | default('*') }}"
    hour: "{{ barman_cron_schedule.hour | default(omit) }}"
    day: "{{ barman_cron_schedule.day | default(omit) }}"
    month: "{{ barman_cron_schedule.month | default(omit) }}"
    weekday: "{{ barman_cron_schedule.weekday | default(omit) }}"

